In [9]:
import numpy as np
import tensorflow_probability as tfp
import tensorflow as tf

In [31]:
probs = [0, 0.5, 1]

In [34]:
dist = tfp.distributions.Bernoulli(probs = probs, dtype=tf.float64)
logits_hat = tf.reduce_mean(dist.sample(10), axis = 0)
logits_hat

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0. , 0.5, 1. ])>

In [35]:
dist = tfp.distributions.Bernoulli(probs = probs, dtype=tf.float64)
logits_hat = tf.reduce_mean(dist.sample(100), axis = 0)
logits_hat

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.  , 0.55, 1.  ])>

In [36]:
dist = tfp.distributions.Bernoulli(probs = probs, dtype=tf.float64)
logits_hat = tf.reduce_mean(dist.sample(1000), axis = 0)
logits_hat

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.   , 0.513, 1.   ])>